### ISSUE TITLE
Running in Non gui mode in linux platform gives CannotResolveClassException

### ISSUE THREAD

**Issue by RatishMohan007** [tilln/jmeter-sshmon#11]
I am trying to run jmeter script with shhmo listener in linux vm using non gui mode command. Gives me the below error while starting up the test. 

Error Details: 

./jmeter.sh -n -t  XXXXX.jmx -l results.jtl -e -o XXXX/TestRun_"`date +%d%m%y%s`"

Error in NonGUIDriver java.lang.IllegalArgumentException: Problem loading XML from:'XXXX.jmx'.
Cause:
CannotResolveClassException: nz.co.breakpoint.jmeter.vizualizers.sshmon.SSHMonCollector

 Detail:com.thoughtworks.xstream.converters.ConversionException:
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       :
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/nz.co.breakpoint.jmeter.vizualizers.sshmon.SSHMonCollector
line number         : 41
version             : 5.4.1

**Comment by tilln** [comment]
Hi @RatishMohan007 

Please double check that the plugin's jar files are actually present in the JMeter lib/ext folder.

**Comment by RatishMohan007** [comment]
Hi @tilln ,

Plugin jar's are available. I have tested it first on gui mode and everything works fine there. This issue is coming only in non gui mode. May be a common issue in headless mode that plugin which use visual graphs do not work there?

**Comment by RatishMohan007** [comment]
One jar file was missing indeed. Closing the issue
