### ISSUE TITLE
Use meter-sshmon to get performance data from Docker instances

### ISSUE THREAD

**Issue by kamal2222ahmed** [tilln/jmeter-sshmon#14]
I am running JMeter in Kubernetes, and wanted to see how it would be possible to get performance data from Docker instances which are generated at run-time.
I have another instance of JMeter Cluster where the VMs ( where the server runs ) has known static IP addresses. In that case it's easy to run meter-sshmon.

**Comment by tilln** [comment]
Hi @kamal2222ahmed 
I would suggest running a shell script before starting JMeter, with some `kubectl` commands to get the pod names you are interested in and their IP addresses (e.g. via `.status.podIPs`).
Then you can assign their values to JMeter properties.
