### ISSUE TITLE
Custom float delimeter or parse comma as dot.

### ISSUE THREAD

**Issue by ruthan** [tilln/jmeter-sshmon#3]
Hello,
i tried plugin i have some problem with parsing float i discovered that its not compatible with float with comma deliver like:
0,01 but it need 0.01 It would be nice to handle that, for these who are not familiar with Linux scripting, sed etc.. Comma delimeter is used for lots of locales.

**Comment by tilln** [comment]
Thanks for reporting this.
Should be fixed in [v1.2](https://github.com/tilln/jmeter-sshmon/releases/tag/1.2)
Please report back if it's working as expected.
